name: Security Dependency & SBOM Scan

on:
  push:
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate SBOM CycloneDX
      - name: Set up JDK and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate SBOM with CycloneDX
        continue-on-error: true
        run: |
          mvn -e org.cyclonedx:cyclonedx-maven-plugin:2.7.6:makeAggregateBom -DskipTests

      # Prepare report directory
      - name: Prepare report folder
        run: |
          rm -rf odc-reports
          mkdir -p odc-reports

      # Run OWASP Dependency-Check
      - name: Run OWASP Dependency-Check
        continue-on-error: true
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -v "${{ github.workspace }}/odc-reports":/report \
            owasp/dependency-check:latest \
            --scan /src \
            --out /report \
            --format "HTML,JSON,XML" \
            --failOnCVSS 0 \
            --project "lab-cyclonedx-dependencycheck"

      # Always upload artefacts
      - name: Upload Dependency-Check Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: odc-reports/

      # Log success message
      - name: Pipeline Complete
        run: echo "✅ Security scan completed successfully. Reports uploaded as artifact."
